name: Zip and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p dist && \
          mkdir -p dist/previews && \
          for dir in src/*/; do
            pushd $dir >/dev/null && \
            mv preview.webp "../../dist/previews/$(basename "$dir").webp" && \
            jq -c ". += {name: \"$(basename "$dir")\"}" meta.json >meta.json.1 && \
            mv -f meta.json.1 meta.json && \
            zip -x "preview.webp" -r "../../dist/$(basename "$dir").zip" . >/dev/null && \
            popd >/dev/null && \
            cat "$dir/meta.json"
          done | \
          jq -sc > dist/templates.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
