name: Zip and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
      - run: |
          mkdir dist
          for dir in src/*/; do
            zip -r "dist/$(basename $dir).zip" "$dir"
          done
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          if: github.ref == 'refs/heads/main'
          publish_dir: ./dist/
